"""add status column

Revision ID: 27f4c06a779e
Revises: fc140bc8e8f7
Create Date: 2026-07-22 16:29:20.738072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f4c06a779e'
down_revision: Union[str, Sequence[str], None] = 'fc140bc8e8f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', sa.Enum('hotel_owner', 'simple_user', name='rolechoices'), nullable=False))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.VARCHAR(length=11), nullable=False))
    op.drop_column('user', 'status')
    # ### end Alembic commands ###
