"""Initial migration

Revision ID: fc140bc8e8f7
Revises: a6bf9a7cf105
Create Date: 2026-07-20 19:56:15.619135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc140bc8e8f7'
down_revision: Union[str, Sequence[str], None] = 'a6bf9a7cf105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Оборачиваем изменение колонки в batch-контекст
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column('role',
            existing_type=sa.VARCHAR(length=6),
            type_=sa.Enum('hotel_owner', 'simple_user', name='rolechoices'),
            existing_nullable=True # или False, в зависимости от вашей модели
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sa.Enum('hotel_owner', 'simple_user', name='rolechoices'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    # ### end Alembic commands ###
